#!/usr/bin/env python
"""Analyze Phase 5 1AXC short MD outputs for pre-registered windows."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def _import_dependencies():
    try:
        import matplotlib.pyplot as plt
        import mdtraj as md
        import numpy as np
        import pandas as pd
    except Exception as exc:  # pragma: no cover - environment-specific
        raise SystemExit(
            "Missing analysis dependencies. Activate env created from "
            "envs/phase5_md_runpod.yml."
        ) from exc
    return md, np, pd, plt


def parse_window(value: str) -> tuple[int, int]:
    left, right = value.split("-", 1)
    return int(left), int(right)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze 1AXC Phase 5 MD trajectories.")
    parser.add_argument(
        "--run-root",
        type=Path,
        default=Path("outputs/phase5_md/time_crunch_1axc_25ns"),
    )
    parser.add_argument(
        "--windows",
        nargs="+",
        default=["239-243", "28-32", "206-210", "134-138"],
    )
    parser.add_argument("--reference-window", default="118-122")
    return parser.parse_args()


def residue_indices_for_window(traj, start: int, end: int) -> list[int]:
    indices = []
    for residue in traj.topology.residues:
        try:
            resseq = int(residue.resSeq)
        except Exception:
            continue
        if start <= resseq <= end and residue.is_protein:
            indices.append(residue.index)
    return indices


def atom_indices_for_residues(traj, residue_indices: list[int], atom_name: str | None = None) -> list[int]:
    residue_set = set(residue_indices)
    atoms = []
    for atom in traj.topology.atoms:
        if atom.residue.index in residue_set and (atom_name is None or atom.name == atom_name):
            atoms.append(atom.index)
    return atoms


def main() -> None:
    args = parse_args()
    md, np, pd, plt = _import_dependencies()

    analysis_dir = args.run_root / "analysis"
    analysis_dir.mkdir(parents=True, exist_ok=True)
    prepared_pdb = args.run_root / "inputs" / "1axc_pcna_apo_from_p21_prepared.pdb"
    if not prepared_pdb.exists():
        raise SystemExit(f"Prepared input PDB not found: {prepared_pdb}")

    windows = [(label, *parse_window(label)) for label in args.windows]
    if args.reference_window:
        windows.append((f"{args.reference_window}_reference", *parse_window(args.reference_window)))

    summaries: list[dict[str, object]] = []
    rmsd_rows = []
    rmsf_rows = []

    for rep_dir in sorted(args.run_root.glob("replicate_*")):
        traj_path = rep_dir / "trajectory.dcd"
        if not traj_path.exists():
            continue
        topology_pdb = rep_dir / "solvated_initial.pdb"
        if not topology_pdb.exists():
            raise SystemExit(
                f"Solvated topology PDB not found for {rep_dir}: {topology_pdb}. "
                "Use trajectories generated by scripts/phase5_run_1axc_openmm.py."
            )
        rep_name = rep_dir.name
        print(f"Loading {traj_path}")
        traj = md.load_dcd(str(traj_path), top=str(topology_pdb))
        protein_atoms = traj.topology.select("protein")
        ca_atoms = traj.topology.select("protein and name CA")
        if len(protein_atoms) == 0 or len(ca_atoms) == 0:
            raise SystemExit(f"No protein/CA atoms found in {traj_path}")
        traj.superpose(traj, 0, atom_indices=ca_atoms)
        rmsd = md.rmsd(traj, traj, 0, atom_indices=ca_atoms)
        for frame_idx, value in enumerate(rmsd):
            rmsd_rows.append(
                {
                    "replicate": rep_name,
                    "frame": frame_idx,
                    "rmsd_nm": float(value),
                }
            )

        for label, start, end in windows:
            residues = residue_indices_for_window(traj, start, end)
            ca_window = atom_indices_for_residues(traj, residues, "CA")
            if not ca_window:
                summaries.append(
                    {
                        "replicate": rep_name,
                        "window": label,
                        "status": "no_ca_atoms_found",
                        "residue_start": start,
                        "residue_end": end,
                    }
                )
                continue
            ref_xyz = traj.xyz[0, ca_window, :]
            diffs = traj.xyz[:, ca_window, :] - ref_xyz[None, :, :]
            per_atom_rmsf = np.sqrt(np.mean(np.sum(diffs * diffs, axis=2), axis=0))
            for atom_idx, value in zip(ca_window, per_atom_rmsf):
                atom = traj.topology.atom(atom_idx)
                rmsf_rows.append(
                    {
                        "replicate": rep_name,
                        "window": label,
                        "chain": atom.residue.chain.id,
                        "residue": int(atom.residue.resSeq),
                        "resname": atom.residue.name,
                        "rmsf_nm": float(value),
                    }
                )
            summaries.append(
                {
                    "replicate": rep_name,
                    "window": label,
                    "status": "ok",
                    "residue_start": start,
                    "residue_end": end,
                    "n_ca_atoms": len(ca_window),
                    "mean_rmsf_nm": float(np.mean(per_atom_rmsf)),
                    "max_rmsf_nm": float(np.max(per_atom_rmsf)),
                    "mean_backbone_rmsd_nm": float(np.mean(rmsd)),
                    "max_backbone_rmsd_nm": float(np.max(rmsd)),
                }
            )

    rmsd_df = pd.DataFrame(rmsd_rows)
    rmsf_df = pd.DataFrame(rmsf_rows)
    summary_df = pd.DataFrame(summaries)
    rmsd_df.to_csv(analysis_dir / "rmsd_timeseries.csv", index=False)
    rmsf_df.to_csv(analysis_dir / "window_rmsf.csv", index=False)
    summary_df.to_csv(analysis_dir / "window_summary.csv", index=False)
    (analysis_dir / "analysis_summary.json").write_text(
        json.dumps(
            {
                "status": "analysis_complete",
                "created_utc": datetime.now(timezone.utc).isoformat(),
                "run_root": str(args.run_root),
                "windows": args.windows,
                "reference_window": args.reference_window,
                "n_replicates_analyzed": int(summary_df["replicate"].nunique()) if not summary_df.empty else 0,
                "limitations": [
                    "Short-timescale exploratory MD only.",
                    "RMSD/RMSF alone do not prove pocket opening or binding.",
                    "No druggability, therapeutic, or validated-site claims are supported.",
                ],
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    if not rmsd_df.empty:
        plt.figure(figsize=(7, 4))
        for rep, grp in rmsd_df.groupby("replicate"):
            plt.plot(grp["frame"], grp["rmsd_nm"], label=rep)
        plt.xlabel("Frame")
        plt.ylabel("Backbone CA RMSD (nm)")
        plt.legend()
        plt.tight_layout()
        plt.savefig(analysis_dir / "rmsd_timeseries.png", dpi=200)
        plt.close()

    if not rmsf_df.empty:
        plot_df = rmsf_df.groupby(["window", "replicate"], as_index=False)["rmsf_nm"].mean()
        plt.figure(figsize=(8, 4))
        for window, grp in plot_df.groupby("window"):
            plt.plot(grp["replicate"], grp["rmsf_nm"], marker="o", label=window)
        plt.xlabel("Replicate")
        plt.ylabel("Mean window CA RMSF (nm)")
        plt.xticks(rotation=30, ha="right")
        plt.legend()
        plt.tight_layout()
        plt.savefig(analysis_dir / "window_rmsf_summary.png", dpi=200)
        plt.close()

    print(f"Analysis outputs written to {analysis_dir}")


if __name__ == "__main__":
    main()
