"""
Docker / Environment Packaging Agent.

Generates reproducible artifacts so external collaborators can replicate the
GNN-PCNA environment:
  (a) docker  — writes a Dockerfile (Python 3.10-slim + system deps for
                BioPython/PyG); optionally builds the image if `docker` is on
                PATH and --build is set. Supports a CUDA variant.
  (b) bundle  — zips a stripped copy of the repo (no raw data, processed
                graphs, MD trajectories, .git, __pycache__, .docx, large
                checkpoints) so a collaborator can recreate the codebase
                without the multi-GB binary payload.

Both subcommands write a manifest.json next to the artifacts that the
orchestrator can attach to its task record.

Usage:
    python agents/docker_packager.py docker  --out data/artifacts/<task_id>
    python agents/docker_packager.py docker  --out data/artifacts/<task_id> --cuda --build
    python agents/docker_packager.py bundle  --out data/artifacts/<task_id>
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import shutil
import subprocess
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

EXCLUDE_DIRS = {
    "data/raw", "data/processed", "data/graphs", "data/trajectories",
    "data/artifacts", "data/cryptosite", "data/pcna",
    ".git", "__pycache__", ".venv", "venv", "node_modules",
    "reports", "checkpoints",  # checkpoints handled separately by size
}
EXCLUDE_GLOBS = [
    "*.docx", "*.dcd", "*.xtc", "*.gro", "*.cif", "*.pdb",
    "*.pt",   # checkpoints / graph tensors (large ones excluded; small ones still skipped to keep bundle reproducible)
    "*.zip", "*.tar", "*.tar.gz", "*.tmp",
    "*.pyc", "*.log",
]
LARGE_CHECKPOINT_BYTES = 50 * 1024 * 1024  # 50 MB


DOCKERFILE_CPU = """\
# GNN-PCNA — reproducible environment (CPU)
# Auto-generated by agents/docker_packager.py on {built_at}

FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PYTHONIOENCODING=utf-8

# System deps required by BioPython, PyG sparse ops, and numerical stack
RUN apt-get update && apt-get install -y --no-install-recommends \\
        build-essential \\
        gcc \\
        g++ \\
        gfortran \\
        git \\
        wget \\
        ca-certificates \\
        libxml2 \\
        libxrender1 \\
        libgomp1 \\
        libglib2.0-0 \\
        libstdc++6 \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps before copying source so layer cache survives code edits
COPY requirements.txt .
RUN pip install --upgrade pip && \\
    pip install -r requirements.txt

# Copy source last (excludes are handled at bundle time, not here)
COPY . .

ENV PYTHONPATH=/app
CMD ["python", "scripts/run_pipeline.py", "--help"]
"""

DOCKERFILE_CUDA = """\
# GNN-PCNA — reproducible environment (CUDA 11.8, PyTorch 2.1)
# Auto-generated by agents/docker_packager.py on {built_at}

FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-runtime

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PYTHONIOENCODING=utf-8

RUN apt-get update && apt-get install -y --no-install-recommends \\
        build-essential \\
        gcc \\
        g++ \\
        gfortran \\
        git \\
        wget \\
        ca-certificates \\
        libxml2 \\
        libxrender1 \\
        libgomp1 \\
        libglib2.0-0 \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \\
    pip install -r requirements.txt

COPY . .

ENV PYTHONPATH=/app
CMD ["python", "scripts/run_pipeline.py", "--help"]
"""


# ── Helpers ──────────────────────────────────────────────────────────────────

@dataclass
class Manifest:
    kind:          str
    created_at:    str
    repo_root:     str
    artifacts:     list[dict]
    metadata:      dict

    def write(self, out_dir: Path) -> Path:
        path = out_dir / "manifest.json"
        path.write_text(
            json.dumps({
                "kind":       self.kind,
                "created_at": self.created_at,
                "repo_root":  self.repo_root,
                "artifacts":  self.artifacts,
                "metadata":   self.metadata,
            }, indent=2),
            encoding="utf-8",
        )
        return path


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _docker_available() -> bool:
    return shutil.which("docker") is not None


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(REPO_ROOT)).replace("\\", "/")
    except ValueError:
        return str(p).replace("\\", "/")


# ── Docker subcommand ────────────────────────────────────────────────────────

def cmd_docker(
    out_dir:  Path,
    cuda:     bool = False,
    build:    bool = False,
    tag:      str  = "gnn-pcna:latest",
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    template     = DOCKERFILE_CUDA if cuda else DOCKERFILE_CPU
    dockerfile   = out_dir / "Dockerfile"
    dockerfile.write_text(template.format(built_at=_now()), encoding="utf-8")

    artifacts = [{
        "name":  "Dockerfile",
        "path":  _rel(dockerfile),
        "kind":  "dockerfile",
        "bytes": dockerfile.stat().st_size,
    }]

    build_info: dict = {"attempted": False, "succeeded": False}
    if build:
        build_info["attempted"] = True
        if not _docker_available():
            build_info["error"] = "docker not on PATH"
            print("[docker_packager] docker not on PATH — skipping image build")
        else:
            print(f"[docker_packager] building image '{tag}' (this may take a while)...")
            log_path = out_dir / "docker_build.log"
            with log_path.open("w", encoding="utf-8") as fh:
                proc = subprocess.run(
                    ["docker", "build", "-t", tag, "-f", str(dockerfile), str(REPO_ROOT)],
                    stdout=fh, stderr=subprocess.STDOUT, text=True,
                )
            build_info["succeeded"] = proc.returncode == 0
            build_info["exit_code"] = proc.returncode
            build_info["log"]       = _rel(log_path)
            build_info["tag"]       = tag
            artifacts.append({
                "name": "docker_build.log", "path": _rel(log_path),
                "kind": "log", "bytes": log_path.stat().st_size,
            })

    manifest = Manifest(
        kind="docker", created_at=_now(), repo_root=str(REPO_ROOT),
        artifacts=artifacts,
        metadata={"variant": "cuda" if cuda else "cpu", "build": build_info},
    )
    manifest.write(out_dir)
    print(f"[docker_packager] Dockerfile -> {dockerfile}")
    return dockerfile


# ── Bundle subcommand ────────────────────────────────────────────────────────

def _should_exclude(rel_posix: str, abs_path: Path) -> bool:
    parts = rel_posix.split("/")
    # Directory-level excludes
    for i in range(1, len(parts) + 1):
        prefix = "/".join(parts[:i])
        if prefix in EXCLUDE_DIRS:
            return True
    # Glob excludes
    name = parts[-1]
    for pat in EXCLUDE_GLOBS:
        if fnmatch.fnmatch(name, pat):
            # large-checkpoint rule: drop only when oversized; small *.pt
            # tensors are still excluded for reproducibility (rebuild from
            # source), so the simple match is fine for both.
            if pat == "*.pt":
                try:
                    if abs_path.stat().st_size >= LARGE_CHECKPOINT_BYTES:
                        return True
                except OSError:
                    return True
                # small .pt — still excluded
                return True
            return True
    return False


def _iter_repo_files() -> list[Path]:
    files: list[Path] = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = _rel(path)
        if _should_exclude(rel, path):
            continue
        files.append(path)
    return files


def cmd_bundle(out_dir: Path, name: str = "gnn-pcna-bundle") -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp     = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    zip_path  = out_dir / f"{name}-{stamp}.zip"

    print(f"[docker_packager] scanning repo for bundle...")
    files = _iter_repo_files()
    print(f"[docker_packager] including {len(files)} files -> {zip_path.name}")

    total_bytes = 0
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for f in files:
            rel = _rel(f)
            try:
                zf.write(f, arcname=rel)
                total_bytes += f.stat().st_size
            except OSError as exc:
                print(f"  [skip] {rel}: {exc}")

    artifacts = [{
        "name":  zip_path.name,
        "path":  _rel(zip_path),
        "kind":  "zip",
        "bytes": zip_path.stat().st_size,
    }]
    manifest = Manifest(
        kind="bundle", created_at=_now(), repo_root=str(REPO_ROOT),
        artifacts=artifacts,
        metadata={
            "file_count":           len(files),
            "uncompressed_bytes":   total_bytes,
            "compressed_bytes":     zip_path.stat().st_size,
            "exclude_dirs":         sorted(EXCLUDE_DIRS),
            "exclude_globs":        EXCLUDE_GLOBS,
            "large_ckpt_threshold": LARGE_CHECKPOINT_BYTES,
        },
    )
    manifest.write(out_dir)
    print(f"[docker_packager] bundle -> {zip_path}")
    return zip_path


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    p   = argparse.ArgumentParser(description="Docker / Environment Packaging Agent")
    sub = p.add_subparsers(dest="cmd", required=True)

    pd = sub.add_parser("docker", help="Generate a reproducible Dockerfile")
    pd.add_argument("--out",  type=Path, required=True, help="Output directory")
    pd.add_argument("--cuda", action="store_true",      help="Use the CUDA variant")
    pd.add_argument("--build", action="store_true",     help="Also `docker build` if docker is on PATH")
    pd.add_argument("--tag",  default="gnn-pcna:latest")

    pb = sub.add_parser("bundle", help="Produce a stripped repo .zip bundle")
    pb.add_argument("--out",  type=Path, required=True, help="Output directory")
    pb.add_argument("--name", default="gnn-pcna-bundle", help="Bundle filename stem")

    args = p.parse_args()

    if args.cmd == "docker":
        cmd_docker(args.out, cuda=args.cuda, build=args.build, tag=args.tag)
    elif args.cmd == "bundle":
        cmd_bundle(args.out, name=args.name)


if __name__ == "__main__":
    main()
