"""Auto-generate the repo-layout section of CODEBASE_MAP.md.

This is a low-effort indexer: it walks the top-level directories, lists each
Python module, and extracts the module docstring's first sentence. Editors can
hand-curate the rest of the file; the indexer only touches the section between
the markers ``<!-- BEGIN AUTOGEN -->`` and ``<!-- END AUTOGEN -->``.

We avoid AST parsing — a simple top-of-file docstring scan is enough for the
map and survives syntax-broken files (which still happens in dev).
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Tuple

_SKIP_DIRS = {
    ".git", "__pycache__", "node_modules", ".venv", "venv", ".pytest_cache",
    ".obsidian", "build", "dist", ".mypy_cache", ".ruff_cache",
}

_TOP_DIRS = (
    "research_os",
    "agents",
    "dashboard",
    "tests",
)

_BEGIN = "<!-- BEGIN AUTOGEN -->"
_END = "<!-- END AUTOGEN -->"


def _extract_first_doc_line(path: Path) -> str:
    """Return the first sentence of a Python module's docstring, or '' if none.

    Be defensive: malformed/binary files should return ''.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""
    # Quick scan: skip leading comments/blank lines, find triple-quoted string.
    m = re.match(r'^\s*(?:#[^\n]*\n|\s)*?("""|\'\'\')([\s\S]*?)\1', text)
    if not m:
        return ""
    doc = m.group(2).strip()
    # First sentence: up to the first period or newline.
    first_line = doc.split("\n", 1)[0].strip()
    if "." in first_line:
        first_line = first_line.split(".", 1)[0] + "."
    return first_line[:160]


def scan_repo(repo_root: "str | Path") -> Dict[str, List[Tuple[str, str]]]:
    """Walk ``_TOP_DIRS`` and return {dir: [(relpath, doc_first_line), ...]}.

    Only Python files are listed. Files are sorted alphabetically. Dirs that
    don't exist are silently skipped.
    """
    root = Path(repo_root)
    result: Dict[str, List[Tuple[str, str]]] = {}
    for top in _TOP_DIRS:
        top_path = root / top
        if not top_path.exists():
            continue
        entries: List[Tuple[str, str]] = []
        for py in sorted(top_path.rglob("*.py")):
            if any(part in _SKIP_DIRS for part in py.parts):
                continue
            rel = py.relative_to(root).as_posix()
            doc = _extract_first_doc_line(py)
            entries.append((rel, doc))
        result[top] = entries
    return result


def render_markdown(scan: Dict[str, List[Tuple[str, str]]]) -> str:
    """Render the scanned tree into a markdown block suitable for the AUTOGEN section."""
    out: List[str] = []
    out.append("> Auto-generated by `research_os.memory.codebase_indexer`. Hand-edits between the BEGIN/END markers will be overwritten on the next refresh.\n")
    for top, entries in scan.items():
        out.append(f"### `{top}/`\n")
        if not entries:
            out.append("(empty)\n")
            continue
        out.append("| Path | First docstring line |")
        out.append("|---|---|")
        for rel, doc in entries:
            doc_cell = doc.replace("|", "\\|") if doc else "—"
            out.append(f"| `{rel}` | {doc_cell} |")
        out.append("")
    return "\n".join(out)


def regenerate_codebase_map(repo_root: "str | Path" = ".") -> Path:
    """Update the AUTOGEN section of ``research_os_memory/CODEBASE_MAP.md``.

    If the file doesn't exist yet, this is a no-op (the bootstrap-written
    version of the file does not yet include the AUTOGEN markers — they are
    inserted on first ``refresh-memory``).

    Returns the path that was written / would have been written.
    """
    root = Path(repo_root)
    map_path = root / "research_os_memory" / "CODEBASE_MAP.md"
    scan = scan_repo(root)
    block = render_markdown(scan)
    autogen = f"{_BEGIN}\n{block}\n{_END}"

    if not map_path.exists():
        # First-time write — synthesize a minimal file with the AUTOGEN block.
        map_path.parent.mkdir(parents=True, exist_ok=True)
        map_path.write_text(
            "# Codebase Map\n\n"
            "Last updated: auto\nUpdated by: research_os.memory.codebase_indexer\nStatus: current\n\n"
            "## Auto-discovered Python modules\n\n"
            f"{autogen}\n",
            encoding="utf-8",
        )
        return map_path

    text = map_path.read_text(encoding="utf-8")
    if _BEGIN in text and _END in text:
        new_text = re.sub(
            re.escape(_BEGIN) + r"[\s\S]*?" + re.escape(_END),
            autogen,
            text,
            count=1,
        )
    else:
        # Append the AUTOGEN section at the end, under a new heading.
        new_text = (
            text.rstrip()
            + "\n\n## Auto-discovered Python modules\n\n"
            + autogen
            + "\n"
        )
    map_path.write_text(new_text, encoding="utf-8")
    return map_path


__all__ = [
    "scan_repo",
    "render_markdown",
    "regenerate_codebase_map",
]
